### ISSUE TITLE
Access to variables

### ISSUE THREAD

**Issue by TxHawks** [davidkpiano/sassport-reference#1]
When importing with `!reference`, are variables defined in the imported partial available line in regular imports?

**Comment by davidkpiano** [comment]
Yes, they should be! All `sassport-reference` does is replace selectors with special placeholder equivalents. Variables, mixins, and functions are untouched and are available.

**Comment by TxHawks** [comment]
Cool! Thanks for the super quick reply!

On another note - it would have been really nice if it sassport was [eyeglass](https://github.com/sass-eyeglass/eyeglass) compatible

**Comment by davidkpiano** [comment]
It's in the works! I made Sassport to be much easier to install and use than Eyeglass, but I am working on making it compatible with existing Eyeglass modules.
